--
-- PostgreSQL database dump
--

\restrict qgqKPaRbBjLwsQ4qIxGcb8ugTHzgM7keahYH77BgxfJLEBP37yOdQ75gnT7GLmK

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: markdown_files; Type: TABLE; Schema: public; Owner: recallforge
--

CREATE TABLE public.markdown_files (
    id bigint NOT NULL,
    content text NOT NULL,
    content_hash character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    environment character varying(255),
    category character varying(255),
    subcategory character varying(255),
    topic_group character varying(255)
);


ALTER TABLE public.markdown_files OWNER TO recallforge;

--
-- Name: markdown_files_id_seq; Type: SEQUENCE; Schema: public; Owner: recallforge
--

ALTER TABLE public.markdown_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.markdown_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: recallforge
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    feedback text NOT NULL,
    question text NOT NULL,
    reviewed_at timestamp(6) without time zone NOT NULL,
    score double precision NOT NULL,
    user_answer text NOT NULL,
    topic_id bigint NOT NULL
);


ALTER TABLE public.reviews OWNER TO recallforge;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: recallforge
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: recallforge
--

CREATE TABLE public.topics (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    memory_score double precision NOT NULL,
    next_review_at timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    markdown_file_id bigint,
    environment character varying(255),
    category character varying(255),
    subcategory character varying(255),
    file_title character varying(255)
);


ALTER TABLE public.topics OWNER TO recallforge;

--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: recallforge
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: markdown_files; Type: TABLE DATA; Schema: public; Owner: recallforge
--

COPY public.markdown_files (id, content, content_hash, filename, uploaded_at, environment, category, subcategory, topic_group) FROM stdin;
2	## JVM / Spring / Framework / Dependency Injection\n\n\n### 1. Dependency Injection (DI)\n\nWith DI an object receive its dependencies from outside.  \nIt doesn't create the dependencies inside the class.   \n\nDI is how IoC is implemented in Spring.\n\n~~~java\nclass NotificationController {\n\n    private final MessageService service;\n\n    public NotificationController() {\n        this.service = new MessageService();  // tightly coupled\n    }\n}\n\nclass NotificationController {\n\n    private final MessageService service;\n\n    // dependency is REQUIRED and immutable\n    public NotificationController(MessageService service) {  // injected\n        this.service = service;\n    }\n}\n~~~\n\n\n### 2. Types of DI\n\n1) Constructor Injection\n\nThis is the recommended way because: \n- dependencies are required\n- object is always valid\n- easier to test\n\n~~~java\nclass MessageService {\n    public String getMessage() {\n        return "Hello DI";\n    }\n}\n\nclass NotificationController {\n\n    private final MessageService messageService;\n\n    // dependency is REQUIRED and immutable\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~\n\n2) Field Injection\n\nNot recommended because: \n- hard to test\n- hidden dependencies\n- not immutable\n\n~~~java\nimport org.springframework.beans.factory.annotation.Autowired;\n\nclass NotificationController {\n\n    @Autowired\n    private MessageService messageService;\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~\n\n\n### 3. IoC using DI\n\n~~~xml\n<dependencies>\n    <dependency>\n        <groupId>org.springframework</groupId>\n        <artifactId>spring-context</artifactId>\n        <version>${spring.version}</version>\n    </dependency>\n</dependencies>\n~~~\n\n@Service: Marks a class as a service component.  \n@Configuration: Indicates that the class contains Spring configuration. \n@ComponentScan: Tells Spring to scan for components in the specified package. \n\nApplicationContext: The Spring container that manages beans and their dependencies.  \n \nIn this example, OrderService depends on PaymentService, and Spring injects   \nthe dependency automatically when creating the OrderService bean.  \n\n~~~java\n/**\n * Dependecny Injection with Spring Framework:\n * ===========================================\n * Spring manages the creation and injection of dependencies.\n */\npackage dependency_injection;\n\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.context.annotation.AnnotationConfigApplicationContext;\nimport org.springframework.context.annotation.ComponentScan;\nimport org.springframework.context.annotation.Configuration;\nimport org.springframework.stereotype.Service;\n\npublic class DependencyInjectionApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context = \n            new AnnotationConfigApplicationContext(AppConfig.class);\n\n        OrderService service = context.getBean(OrderService.class);\n        service.processOrder();\n            // Payment executed ...\n            // Order processed.\n    }\n}\n\n@Configuration\n@ComponentScan(basePackages = "dependency_injection")\nclass AppConfig {\n}\n\n@Service\nclass PaymentService {\n    \n    public void pay() {\n        System.out.println("Payment executed ...");\n    }\n}\n\n@Service\nclass OrderService {\n\n    private final PaymentService paymentService;\n\n    public OrderService(PaymentService paymentService) {\n        this.paymentService = paymentService;\n    }\n\n    public void processOrder() {\n        paymentService.pay();\n        System.out.println("Order processed.");\n    }\n}\n~~~	7bb63aa2eedf349309da5f320b91a9be757e38a2dd6aba5693538c71f34dd61a	README.md	2026-05-31 13:58:11.334173	JVM	Spring	Framework	Dependency Injection
1	## JVM / Spring / Framework / Inversion of Control\n\n\n### 1. Inversion of Control (IoC)\n\nWith IoC the control of `creating and wiring` objects is moved out of your code.   \n\nIn plain java, we often wire objects ourselves (with new).  \nIn Spring, the IoC `container` creates objects and connects their dependencies.  \nIn Spring, that container is commonly represented by `ApplicationContext`.  \n\nSpring's container is responsible for instantianting, configuring, and assembling `beans`.   \n\n\n### 2. Manual creation (objects)\n\nWe crete dependencies manually with new keyword.  \nThis is simple for small programs, but in larger apps it becomes hard to manage.  \n\n~~~java\n/**\n * Manual Creation (plain Java)\n * ============================\n */\npackage manual_creation;\n\npublic class ManualCreationApp {\n    public static void main(String[] args) {\n\n        MessageService service = new MessageService();\n\n        NotificationController controller = new NotificationController(service);\n        controller.print();  // Hello from Service / Manual Creation\n    }\n}\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Manual Creation";\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~\n\n### 3. Factory pattern\n\nUsing Factory Pattern the creation is centralized, but still controlled by our code. \n\n~~~java\n/**\n * Factory pattern (plain Java)\n * ============================\n */\npackage factory_pattern;\n\npublic class FactoryPatternApp {\n    public static void main(String[] args) {\n\n        NotificationController controller = AppFactory.createNotificationController();\n        controller.print();  // Hello from MessageService\n    }\n}\n\nclass AppFactory {\n    public static NotificationController createNotificationController() {\n\n        MessageService service = new MessageService();\n        return new NotificationController(service);\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n\n}\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Factory Pattern";\n    }\n}\n~~~\n\n\n### 4. Spring IoC\n\nSpring Framework does the important wiring work:\n\n- creates MessageService\n- creates NotificationController\n- injects MessageService into NotificationController\n\nThat is IoC: control moved from you app code to the Spring container.  \n\nSpring supports Java-based configuration through `@Configuration` and `@Bean`,  \nand `ApplicationContext` is the central IoC container interface.  \n\n~~~xml\n<!-- ========================================\n     Maven build file for plain Spring Framework\n     No Spring Boot\n     Java 17\n     ======================================== -->\n<project xmlns="http://maven.apache.org/POM/4.0.0"\n         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0\n         https://maven.apache.org/xsd/maven-4.0.0.xsd">\n    <modelVersion>4.0.0</modelVersion>\n\n    <groupId>com.example.ioc</groupId>\n    <artifactId>demo</artifactId>\n    <version>1.0</version>\n    <name>ioc</name>\n\n    <properties>\n        <maven.compiler.source>17</maven.compiler.source>\n        <maven.compiler.target>17</maven.compiler.target>\n        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n        <spring.version>6.2.17</spring.version>\n    </properties>\n\n    <dependencies>\n        <dependency>\n            <groupId>org.springframework</groupId>\n            <artifactId>spring-context</artifactId>\n            <version>${spring.version}</version>\n        </dependency>\n    </dependencies>\n</project>\n~~~\n\n~~~java\npackage spring_ioc;\n\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.context.annotation.AnnotationConfigApplicationContext;\nimport org.springframework.context.annotation.Bean;\nimport org.springframework.context.annotation.Configuration;\n\npublic class SpringIocApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context =\n                 new AnnotationConfigApplicationContext(AppConfig.class);\n\n        NotificationController controller = \n            context.getBean(NotificationController.class);\n\n        controller.print();  // Hello from Service / Spring IoC\n    }\n}\n\n// Configuration\n\n@Configuration\nclass AppConfig {\n\n    @Bean\n    MessageService messageService() {\n        return new MessageService();\n    }\n\n    @Bean\n    NotificationController notificationController(MessageService messageService) {\n        return new NotificationController(messageService);\n    }\n}\n\n// Beans\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Spring IoC";\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~\n\n### 5. Spring Boot\n\nSpring Boot still uses Spring IoC and ApplicationContext.  \n\nInstead of manually defining many beans, Spring Boot configures common infrastructure automatically.   \nSpring Boot does not replace Spring Framework - it sits on top of Spring and makes setup faster.  \n\n~~~xml\n<!-- Spring Boot -->\n<dependency>\n    <groupId>org.springframework.boot</groupId>\n    <artifactId>spring-boot-starter</artifactId>\n</dependency>\n~~~\n~~~java\npackage spring_boot;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.stereotype.Component;\nimport org.springframework.stereotype.Service;\n\n@SpringBootApplication\npublic class SpringBootApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context =\n                SpringApplication.run(SpringBootApp.class, args);\n\n        NotificationController controller = \n            context.getBean(NotificationController.class);\n\n        controller.print();  // Hello from Service / Spring Boot\n    }\n}\n\n@Service\nclass MessageService {\n\n    public String getMessage() {\n        return "Hello from Service / Spring Boot";\n    }\n}\n\n@Component\nclass NotificationController {\n\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~	15caca75817c8dec32ce9be5342ed52be66321fae2e04c14ff90d8a54f6c9659	README.md	2026-05-31 13:57:43.834374	JVM	Spring	Framework	Inversion of Control
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: recallforge
--

COPY public.reviews (id, feedback, question, reviewed_at, score, user_answer, topic_id) FROM stdin;
\.


--
-- Data for Name: topics; Type: TABLE DATA; Schema: public; Owner: recallforge
--

COPY public.topics (id, content, created_at, memory_score, next_review_at, title, updated_at, markdown_file_id, environment, category, subcategory, file_title) FROM stdin;
2	We crete dependencies manually with new keyword.  \nThis is simple for small programs, but in larger apps it becomes hard to manage.  \n\n~~~java\n/**\n * Manual Creation (plain Java)\n * ============================\n */\npackage manual_creation;\n\npublic class ManualCreationApp {\n    public static void main(String[] args) {\n\n        MessageService service = new MessageService();\n\n        NotificationController controller = new NotificationController(service);\n        controller.print();  // Hello from Service / Manual Creation\n    }\n}\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Manual Creation";\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~	2026-05-31 13:57:43.914007	0.5	2026-05-31 13:57:43.913984	2. Manual creation (objects)	2026-05-31 13:57:43.914014	1	JVM	Spring	Framework	Inversion of Control
3	Using Factory Pattern the creation is centralized, but still controlled by our code. \n\n~~~java\n/**\n * Factory pattern (plain Java)\n * ============================\n */\npackage factory_pattern;\n\npublic class FactoryPatternApp {\n    public static void main(String[] args) {\n\n        NotificationController controller = AppFactory.createNotificationController();\n        controller.print();  // Hello from MessageService\n    }\n}\n\nclass AppFactory {\n    public static NotificationController createNotificationController() {\n\n        MessageService service = new MessageService();\n        return new NotificationController(service);\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n\n}\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Factory Pattern";\n    }\n}\n~~~	2026-05-31 13:57:43.92083	0.5	2026-05-31 13:57:43.920812	3. Factory pattern	2026-05-31 13:57:43.920836	1	JVM	Spring	Framework	Inversion of Control
4	Spring Framework does the important wiring work:\n\n- creates MessageService\n- creates NotificationController\n- injects MessageService into NotificationController\n\nThat is IoC: control moved from you app code to the Spring container.  \n\nSpring supports Java-based configuration through `@Configuration` and `@Bean`,  \nand `ApplicationContext` is the central IoC container interface.  \n\n~~~xml\n<!-- ========================================\n     Maven build file for plain Spring Framework\n     No Spring Boot\n     Java 17\n     ======================================== -->\n<project xmlns="http://maven.apache.org/POM/4.0.0"\n         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0\n         https://maven.apache.org/xsd/maven-4.0.0.xsd">\n    <modelVersion>4.0.0</modelVersion>\n\n    <groupId>com.example.ioc</groupId>\n    <artifactId>demo</artifactId>\n    <version>1.0</version>\n    <name>ioc</name>\n\n    <properties>\n        <maven.compiler.source>17</maven.compiler.source>\n        <maven.compiler.target>17</maven.compiler.target>\n        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n        <spring.version>6.2.17</spring.version>\n    </properties>\n\n    <dependencies>\n        <dependency>\n            <groupId>org.springframework</groupId>\n            <artifactId>spring-context</artifactId>\n            <version>${spring.version}</version>\n        </dependency>\n    </dependencies>\n</project>\n~~~\n\n~~~java\npackage spring_ioc;\n\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.context.annotation.AnnotationConfigApplicationContext;\nimport org.springframework.context.annotation.Bean;\nimport org.springframework.context.annotation.Configuration;\n\npublic class SpringIocApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context =\n                 new AnnotationConfigApplicationContext(AppConfig.class);\n\n        NotificationController controller = \n            context.getBean(NotificationController.class);\n\n        controller.print();  // Hello from Service / Spring IoC\n    }\n}\n\n// Configuration\n\n@Configuration\nclass AppConfig {\n\n    @Bean\n    MessageService messageService() {\n        return new MessageService();\n    }\n\n    @Bean\n    NotificationController notificationController(MessageService messageService) {\n        return new NotificationController(messageService);\n    }\n}\n\n// Beans\n\nclass MessageService {\n    public String getMessage() {\n        return "Hello from Service / Spring IoC";\n    }\n}\n\nclass NotificationController {\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~	2026-05-31 13:57:43.924419	0.5	2026-05-31 13:57:43.924403	4. Spring IoC	2026-05-31 13:57:43.924425	1	JVM	Spring	Framework	Inversion of Control
5	Spring Boot still uses Spring IoC and ApplicationContext.  \n\nInstead of manually defining many beans, Spring Boot configures common infrastructure automatically.   \nSpring Boot does not replace Spring Framework - it sits on top of Spring and makes setup faster.  \n\n~~~xml\n<!-- Spring Boot -->\n<dependency>\n    <groupId>org.springframework.boot</groupId>\n    <artifactId>spring-boot-starter</artifactId>\n</dependency>\n~~~\n~~~java\npackage spring_boot;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.stereotype.Component;\nimport org.springframework.stereotype.Service;\n\n@SpringBootApplication\npublic class SpringBootApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context =\n                SpringApplication.run(SpringBootApp.class, args);\n\n        NotificationController controller = \n            context.getBean(NotificationController.class);\n\n        controller.print();  // Hello from Service / Spring Boot\n    }\n}\n\n@Service\nclass MessageService {\n\n    public String getMessage() {\n        return "Hello from Service / Spring Boot";\n    }\n}\n\n@Component\nclass NotificationController {\n\n    private final MessageService messageService;\n\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~	2026-05-31 13:57:43.92781	0.5	2026-05-31 13:57:43.927794	5. Spring Boot	2026-05-31 13:57:43.927815	1	JVM	Spring	Framework	Inversion of Control
6	With DI an object receive its dependencies from outside.  \nIt doesn't create the dependencies inside the class.   \n\nDI is how IoC is implemented in Spring.\n\n~~~java\nclass NotificationController {\n\n    private final MessageService service;\n\n    public NotificationController() {\n        this.service = new MessageService();  // tightly coupled\n    }\n}\n\nclass NotificationController {\n\n    private final MessageService service;\n\n    // dependency is REQUIRED and immutable\n    public NotificationController(MessageService service) {  // injected\n        this.service = service;\n    }\n}\n~~~	2026-05-31 13:58:11.344016	0.5	2026-05-31 13:58:11.343996	1. Dependency Injection (DI)	2026-05-31 13:58:11.344034	2	JVM	Spring	Framework	Dependency Injection
7	1) Constructor Injection\n\nThis is the recommended way because: \n- dependencies are required\n- object is always valid\n- easier to test\n\n~~~java\nclass MessageService {\n    public String getMessage() {\n        return "Hello DI";\n    }\n}\n\nclass NotificationController {\n\n    private final MessageService messageService;\n\n    // dependency is REQUIRED and immutable\n    public NotificationController(MessageService messageService) {\n        this.messageService = messageService;\n    }\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~\n\n2) Field Injection\n\nNot recommended because: \n- hard to test\n- hidden dependencies\n- not immutable\n\n~~~java\nimport org.springframework.beans.factory.annotation.Autowired;\n\nclass NotificationController {\n\n    @Autowired\n    private MessageService messageService;\n\n    public void print() {\n        System.out.println(messageService.getMessage());\n    }\n}\n~~~	2026-05-31 13:58:11.348855	0.5	2026-05-31 13:58:11.348833	2. Types of DI	2026-05-31 13:58:11.348861	2	JVM	Spring	Framework	Dependency Injection
8	~~~xml\n<dependencies>\n    <dependency>\n        <groupId>org.springframework</groupId>\n        <artifactId>spring-context</artifactId>\n        <version>${spring.version}</version>\n    </dependency>\n</dependencies>\n~~~\n\n@Service: Marks a class as a service component.  \n@Configuration: Indicates that the class contains Spring configuration. \n@ComponentScan: Tells Spring to scan for components in the specified package. \n\nApplicationContext: The Spring container that manages beans and their dependencies.  \n \nIn this example, OrderService depends on PaymentService, and Spring injects   \nthe dependency automatically when creating the OrderService bean.  \n\n~~~java\n/**\n * Dependecny Injection with Spring Framework:\n * ===========================================\n * Spring manages the creation and injection of dependencies.\n */\npackage dependency_injection;\n\nimport org.springframework.context.ApplicationContext;\nimport org.springframework.context.annotation.AnnotationConfigApplicationContext;\nimport org.springframework.context.annotation.ComponentScan;\nimport org.springframework.context.annotation.Configuration;\nimport org.springframework.stereotype.Service;\n\npublic class DependencyInjectionApp {\n    public static void main(String[] args) {\n\n        ApplicationContext context = \n            new AnnotationConfigApplicationContext(AppConfig.class);\n\n        OrderService service = context.getBean(OrderService.class);\n        service.processOrder();\n            // Payment executed ...\n            // Order processed.\n    }\n}\n\n@Configuration\n@ComponentScan(basePackages = "dependency_injection")\nclass AppConfig {\n}\n\n@Service\nclass PaymentService {\n    \n    public void pay() {\n        System.out.println("Payment executed ...");\n    }\n}\n\n@Service\nclass OrderService {\n\n    private final PaymentService paymentService;\n\n    public OrderService(PaymentService paymentService) {\n        this.paymentService = paymentService;\n    }\n\n    public void processOrder() {\n        paymentService.pay();\n        System.out.println("Order processed.");\n    }\n}\n~~~	2026-05-31 13:58:11.353678	0.5	2026-05-31 13:58:11.353658	3. IoC using DI	2026-05-31 13:58:11.353684	2	JVM	Spring	Framework	Dependency Injection
1	With IoC the control of `creating and wiring` objects is moved out of your code.   \n\nIn plain java, we often wire objects ourselves (with new).  \nIn Spring, the IoC `container` creates objects and connects their dependencies.  \nIn Spring, that container is commonly represented by `ApplicationContext`.  \n\nSpring's container is responsible for instantianting, configuring, and assembling `beans`.	2026-05-31 13:57:43.906373	0.5	2026-05-31 13:57:43.906348	1. Inversion of Control (IoC)	2026-05-31 13:59:52.945218	1	JVM	Spring	Framework	Inversion of Control
\.


--
-- Name: markdown_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: recallforge
--

SELECT pg_catalog.setval('public.markdown_files_id_seq', 2, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: recallforge
--

SELECT pg_catalog.setval('public.reviews_id_seq', 1, false);


--
-- Name: topics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: recallforge
--

SELECT pg_catalog.setval('public.topics_id_seq', 8, true);


--
-- Name: markdown_files markdown_files_pkey; Type: CONSTRAINT; Schema: public; Owner: recallforge
--

ALTER TABLE ONLY public.markdown_files
    ADD CONSTRAINT markdown_files_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: recallforge
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: recallforge
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: topics fkc5tuh8x1p1enpx54b1kvn5f3e; Type: FK CONSTRAINT; Schema: public; Owner: recallforge
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fkc5tuh8x1p1enpx54b1kvn5f3e FOREIGN KEY (markdown_file_id) REFERENCES public.markdown_files(id);


--
-- Name: reviews fkcxk0c2gseajga5if854rbd2nx; Type: FK CONSTRAINT; Schema: public; Owner: recallforge
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcxk0c2gseajga5if854rbd2nx FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- PostgreSQL database dump complete
--

\unrestrict qgqKPaRbBjLwsQ4qIxGcb8ugTHzgM7keahYH77BgxfJLEBP37yOdQ75gnT7GLmK

